#' Binary Item Parameter Data Frame # 1. (18 items)\cr
#'
#' @details
#' \preformatted{
#' name type ncat   p1   p2   p3
#'   Q1    B    2  1.0 -1.0  0.0
#'   Q2    B    2  1.0  0.0  0.0
#'   Q3    B    2  1.0  1.0  0.0
#'   Q4    B    2  1.0 -1.0  0.0
#'   Q5    B    2  1.0  0.0  0.0
#'   Q6    B    2  1.0  1.0  0.0
#'   Q7    B    2  1.3 -1.0  0.0
#'   Q8    B    2  1.3  0.0  0.0
#'   Q9    B    2  1.3  1.0  0.0
#'   Q10   B    2  1.3 -1.0  0.0
#'   Q11   B    2  1.3  0.0  0.0
#'   Q12   B    2  1.3  1.0  0.0
#'   Q13   B    2  0.7 -1.0  0.0
#'   Q14   B    2  0.7  0.0  0.0
#'   Q15   B    2  0.7  1.0  0.0
#'   Q16   B    2  0.7 -1.0  0.0
#'   Q17   B    2  0.7  0.0  0.0
#'   Q18   B    2  0.7  1.0  0.0
#'   }
#'    \cr
#'    item type = "B" \cr
#'    ncat is the max # of categories \cr
#'
#'
#' @format A data frame with 18 rows and 6 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope: a}
#'  \item{p2}{num: 2nd  item parameter: threshold: b}
#'  \item{p3}{num: 3rd item parameter: lower asymptote: c}
#' }
#' @source Generated by author.
#'
"paramB1"



#' Binary Item Parameter Data Frame # 2. (18 items)\cr
#'
#' @details
#' \preformatted{
#' name type ncat   p1   p2   p3
#'   Q1    B3    2  1.0 -1.0  0.0
#'   Q2    B3    2  1.0  0.0  0.0
#'   Q3    B3    2  1.0  1.0  0.0
#'   Q4    B3    2  1.0 -1.0  0.0
#'   Q5    B3    2  1.0  0.0  0.0
#'   Q6    B3    2  1.0  1.0  0.0
#'   Q7    B3    2  1.3 -1.0  0.0
#'   Q8    B3    2  1.3  0.0  0.0
#'   Q9    B3    2  1.3  1.0  0.0
#'   Q10   B3    2  1.3 -1.0  0.0
#'   Q11   B3    2  1.3  0.0  0.0
#'   Q12   B3    2  1.3  1.0  0.0
#'   Q13   B3    2  0.7 -1.0  0.0
#'   Q14   B3    2  0.7  0.0  0.0
#'   Q15   B3    2  0.7  1.0  0.0
#'   Q16   B3    2  0.7 -1.0  0.0
#'   Q17   B3    2  0.7  0.0  0.0
#'   Q18   B3    2  0.7  1.0  0.0
#'   }
#'    \cr
#'    item type = "B"  (3PLM)\cr
#'    ncat is the max # of categories \cr
#'
#'
#' @format A data frame with 18 rows and 6 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope: a}
#'  \item{p2}{num: 2nd  item parameter: threshold: b}
#'  \item{p3}{num: 3rd item parameter: lower asymptote: c}
#' }
#' @source Generated by author.
#'
"paramB2"






#' Small Item Parameter Data Frame # 1. (3 items)\cr
#'
#' @details
#' \preformatted{
#' name type ncat  p1  p2   p3   p4
#'   Q1    B    2 0.9  0.0  NA   NA
#'   Q2   B3    2 1.0  0.0 0.2   NA
#'   Q3    G    4 1.0 -2.0 0.0  2.0
#'   Q4    P    4 0.8 -2.0 0.0  2.0
#'   }
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'
#'
#' @format A data frame with 4 rows and 7 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope}
#'  \item{p2}{num: 2nd  item parameter}
#'  \item{p3}{num: 3rd item parameter}
#'  \item{p4}{num: 4th item parameter}
#' }
#' @source Generated by author.
#'
"paramS1"


#' Small Item Parameter Data Frame # 2. (8 items)\cr
#'
#' @details
#' \preformatted{
#'  name type ncat  p1  p2   p3 p4
#'   Q11    B    2 0.9  0.0  NA NA
#'   Q12    B    2 0.9  1.0  NA NA
#'   Q21   B3    2 1.0  0.0 0.2 NA
#'   Q22   B3    2 1.0  1.0 0.2 NA
#'   Q31    G    3 1.0 -1.0 1.0 NA
#'   Q32    G    4 1.0 -2.0 0.0  2.0
#'   Q41    P    3 0.8 -1.0 1.0 NA
#'   Q42    P    4 0.8 -2.0 0.0  2.0
#'   }
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'
#'
#' @format A data frame with 8 rows and 7 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope}
#'  \item{p2}{num: 2nd  item parameter}
#'  \item{p3}{num: 3rd item parameter}
#'  \item{p4}{num: 4th item parameter}
#' }
#' @source Generated by author.
#'
"paramS2"


#' Small Item Parameter Data Frame # 3.  (20 items)\cr
#'
#' @details
#' \preformatted{
#' name  type ncat p1        p2         p3         p4
#' QB1   B   2    1         -1           NA        NA
#' QB2   B2  2    1          0           NA        NA
#' QB3   B2  2    1          1           NA        NA
#' QB4   B3  2    .8         1           .2        NA
#' QG1   G   3    1.0       -2          0          NA
#' QG2   G   3    1.0       -1          1          NA
#' QG3   G   3    1.0        0          2          NA
#' QG4   G   3    0.7       -3          1          NA
#' QG5   G   3    0.7       -2          2          NA
#' QG6   G   3    0.7       -1          3          NA
#' QG7   G   4    1.0       -2          0           2
#' QG8   G   4    0.7       -2          0           2
#' QPN1  PN  3    0.7344    -2.1150    -1.0310     NA
#' QPN2  PN  3    0.8020    -0.9985     0.0000     NA
#' QPN3  PN  3    0.8237     0.0790     0.9871     NA
#' QPN4  PN  3    0.5998    -3.1934    -1.0192     NA
#' QPN5  PN  3    0.6258    -2.1071     0.0000     NA
#' QPN6  PN  3    0.6319    -1.0512     0.9921     NA
#' QPN7  PN  4    0.6483    -2.3307    -1.0627      0
#' QPN8  PN  4    0.4231    -1.9974    -1.0154      0
#'   }
#'    \cr
#'    item type = "B" or "B3" or "G" or "PN" \cr
#'    ncat is the max # of categories \cr
#'
#'
#' @format A data frame with 20 rows and 7 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope}
#'  \item{p2}{num: 2nd  item parameter}
#'  \item{p3}{num: 3rd item parameter}
#'  \item{p4}{num: 4th item parameter}
#' }
#' @source Generated by author.
#'
"paramS3"


#' Small Item Parameter Data Frame for Testing cala and calr #2.\cr
#'
#' This data frame contains three sets of estimated item parameters of
#' various types of items distributed across three test forms. \cr
#' The item parameters were estimated independently for each form.
#'
#' @details
#'  gfid name type ncat        p1          p2         p3       p4 \cr
#' form1  QB1   B2    2 1.0000000 -1.00000000  0.0000000       NA \cr
#' form1  QB2   B2    2 1.0000000  0.00000000  0.3000000       NA \cr
#' form1  QB4   B3    2 0.8000000  1.00000000  0.2000000       NA \cr
#' form1  QG1    G    3 1.0000000 -2.00000000  0.0000000       NA \cr
#' form1  QG2    G    3 1.0000000 -1.00000000  1.0000000       NA \cr
#' form1  QG3    G    3 1.0000000  0.00000000  2.0000000       NA \cr
#' form1  QG4    G    3 0.7000000 -3.00000000  1.0000000       NA \cr
#' form1  QG5    G    3 0.7000000 -2.00000000  2.0000000       NA \cr
#' form1  QG6    G    3 0.7000000 -1.00000000  3.0000000       NA \cr
#' form1  QG8    G    4 0.7000000 -2.00000000  0.0000000 2.000000 \cr
#' form1  QP1    P    3 0.7344000 -2.11500000  0.0530000       NA \cr
#' form1  QP2    P    3 0.8020000 -0.99850000  0.9985000       NA \cr
#' form1  QP3    P    3 0.8237000  0.07900000  1.8952000       NA \cr
#' form1  QP4    P    3 0.5998000 -3.19340000  1.1550000       NA \cr
#' form1  QP5    P    3 0.6258000 -2.10710000  2.1071000       NA \cr
#' form1  QP6    P    3 0.6319000 -1.05120000  3.0354000       NA \cr
#' form1  QP7    P    4 0.6483000 -2.33070000  0.2053000 2.125400 \cr
#' form2  QB1   B2    2 0.9736860 -2.50974572  0.0000000       NA \cr
#' form2  QB3   B3    2 0.7560111  0.25955944  0.2991986       NA \cr
#' form2  QG1    G    3 0.7700730 -3.85306557 -1.1357144       NA \cr
#' form2  QG3    G    3 1.0288158 -1.12433239  1.4054329       NA \cr
#' form2  QG5    G    3 0.8033210 -3.74832196  1.5112735       NA \cr
#' form2  QG7    G    4 0.9167175 -3.81423155 -1.1428328 1.613180 \cr
#' form2  QP1    P    3 0.7256544 -4.10048328 -1.2231697       NA \cr
#' form2  QP3    P    3 0.6181345 -1.06795481  1.0809555       NA \cr
#' form2  QP5    P    3 0.5632958 -3.93255199  1.3176705       NA \cr
#' form2  QP7    P    4 0.5277231 -4.28903421 -0.7262809 1.149967 \cr
#' form2  QB2   B2    2 0.9845137 -1.15960242  0.3000000       NA \cr
#' form2  QG2    G    3 0.9434385 -2.55422669  0.2331392       NA \cr
#' form3  QB2   B2    2 1.5268054  1.01997505  0.3000000       NA \cr
#' form3  QB4   B3    2 1.3534871  1.58018603  0.4643032       NA \cr
#' form3  QG2    G    3 1.5803144  0.16910510  1.5452752       NA \cr
#' form3  QG4    G    3 1.1897892 -1.44156820  1.6082322       NA \cr
#' form3  QG6    G    3 0.9773134  0.18749580  3.2815727       NA \cr
#' form3  QG8    G    4 1.2314105 -0.73990378  1.0218542 2.315625 \cr
#' form3  QP2    P    3 1.1810182  0.04046525  1.5351101       NA \cr
#' form3  QP4    P    3 0.9534385 -1.49477547  1.6427269       NA \cr
#' form3  QP6    P    3 1.0670629  0.07743022  3.4615809       NA \cr
#' form3  QP8    P    4 0.6973531 -0.56943438  0.9358040 2.118880 \cr
#' form3  QB1   B2    2 1.6124478  0.09865741  0.0000000       NA
#'
#'
#' @format A data frame with 40 rows and 8 variables. \cr
#' Basically, the structure is the same as the parameter data frame \cr
#' except that the first column containing the form name is added.\cr
#' \describe{
#'  \item{gfid}{character:  Form name}
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope}
#'  \item{p2}{num: 2nd  item parameter}
#'  \item{p3}{num: 3rd item parameter}
#' }
#' @source Generated by author.
#'
"paramCal2"


#' Small Item Parameter Data Frame for Testing cala and calr #1.\cr
#'
#' This data frame contains three sets of estimated item parameters of
#' binary items distributed across three test forms. \cr
#' The item parameters were estimated independently for each form.

#'
#' @details
#'     gfid name type ncat        p1          p2        p3 \cr
#' form1  QB1   B2    2 1.0000000 -1.00000000 0.0000000 \cr
#' form1  QB2   B2    2 1.0000000  0.00000000 0.3000000 \cr
#' form1  QB4   B3    2 0.8000000  1.00000000 0.2000000 \cr
#' form1  QB5   B2    2 1.0000000 -1.30000000 0.0000000 \cr
#' form1  QB6   B2    2 1.0000000  0.30000000 0.3000000 \cr
#' form1  QB7   B3    2 1.0000000  1.30000000 0.2000000 \cr
#' form1  QB8   B3    2 0.8000000  0.70000000 0.2000000 \cr
#' form1 QB11   B2    2 1.2000000 -1.00000000 0.0000000 \cr
#' form1 QB12   B2    2 1.2000000  0.00000000 0.3000000 \cr
#' form1 QB14   B3    2 1.0000000  1.00000000 0.2000000 \cr
#' form1 QB15   B2    2 0.8000000 -1.00000000 0.0000000 \cr
#' form1 QB16   B2    2 0.8000000  0.00000000 0.3000000 \cr
#' form1 QB17   B3    2 0.8000000  1.00000000 0.2000000 \cr
#' form1 QB18   B3    2 0.7000000  1.00000000 0.2000000 \cr
#' form2  QB1   B2    2 0.9736860 -2.57272092 0.0000000 \cr
#' form2  QB3   B3    2 0.7560111  0.04149805 0.3905005 \cr
#' form2  QB5   B2    2 0.7700730 -2.90974572 0.0000000 \cr
#' form2  QB7   B3    2 1.0288158  0.65955944 0.2237003 \cr
#' form2 QB11   B2    2 1.1783210 -2.51973224 0.0000000 \cr
#' form2 QB13   B3    2 1.0667175  0.20900095 0.4426091 \cr
#' form2 QB15   B2    2 0.7748544 -2.41498863 0.0000000 \cr
#' form2 QB17   B3    2 0.6003595  0.18576845 0.2764597 \cr
#' form2  QB2   B2    2 0.9845137 -1.11132899 0.3000000 \cr
#' form2  QB6   B2    2 0.9434385 -0.75960242 0.3000000 \cr
#' form3  QB2   B2    2 1.4515893  0.91079758 0.3000000 \cr
#' form3  QB4   B3    2 1.2179065  1.75344958 0.2100962 \cr
#' form3  QB6   B2    2 1.5139847  1.16847211 0.3000000 \cr
#' form3  QB8   B3    2 1.1706377  1.56182045 0.3502745 \cr
#' form3 QB12   B2    2 1.6937542  0.99698111 0.3000000 \cr
#' form3 QB14   B3    2 1.4473557  1.75645583 0.3786156 \cr
#' form3 QB16   B2    2 1.1834637  0.79398007 0.3000000 \cr
#' form3 QB18   B3    2 0.9699614  1.79807714 0.4093079 \cr
#' form3  QB1   B2    2 1.4712936  0.17616872 0.0000000#'
#'
#' @format A data frame with 33 rows and 8 variables. \cr
#' Basically, the structure is the same as the parameter data frame \cr
#' except that the first column containing the form name is added.\cr
#' \describe{
#'  \item{gfid}{character:  Form name}
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{p1}{num: First item parameter: slope}
#'  \item{p2}{num: 2nd  item parameter}
#'  \item{p3}{num: 3rd item parameter}
#' }
#' @source Generated by author.
#'
"paramCal1"








#' Small Item Weight Data Frame # 1 \cr
#' To be used in conjunction with paramS1.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q1    B    2    1    0    1 ,, \cr
#' Q2    B3   2    1    0    1 ,, \cr
#' Q3    G    4    1    0    1    2    3 \cr
#' Q4    P    4    1    0    1    2    3 \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. (all equal)\cr
#'    v's are the category weight (all natural)
#'
#'
#' @format A data frame with 4 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS1"

#' Small Item Weight Data Frame # 2.\cr
#' To be used in conjunction with paramS1.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q1    B    2    1    0    1 ,, \cr
#' Q2    B3   2    2    0    1 ,, \cr
#' Q3    G    4    1    0    1    2    3 \cr
#' Q4    P    4    2    0    1    2    3 \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. \cr
#'    v's are the category weight (all natural)
#'
#'
#' @format A data frame with 4 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS11"


#' Small Item Weight Data Frame # 3.\cr
#' To be used in conjunction with paramS1.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q1    B    2    1    0    1 ,, \cr
#' Q2    B3   2    1    0    2 ,, \cr
#' Q3    G    4    1    0    1    2    5 \cr
#' Q4    P    4    1    0    0    0    1 \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. (all equal)\cr
#'    v's are the category weight
#'
#'
#' @format A data frame with 4 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS12"


#' Small Item Weight Data Frame # 4.\cr
#' To be used in conjunction with paramS2.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q11    B    2   1    0    1 ,, \cr
#' Q12    B    2   1    0    1 ,, \cr
#' Q21    B3   2   1    0    1 ,, \cr
#' Q22    B3   2   1    0    1 ,, \cr
#' Q31    G    3   1    0    1    2    3 \cr
#' Q32    G    4   1    0    1    2    3 \cr
#' Q41    P    3   1    0    1    2    3 \cr
#' Q42    P    4   1    0    1    2    3 \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. (all equal)\cr
#'    v's are the category weight (all natural)
#'
#'
#' @format A data frame with 8 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS2"


#' Small Item Weight Data Frame # 5.\cr
#' To be used in conjunction with paramS2.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q11    B    2   1    0    1 ,, \cr
#' Q12    B    2   2    0    1 ,, \cr
#' Q21    B3   2   1    0    1 ,, \cr
#' Q22    B3   2   2    0    1 ,, \cr
#' Q31    G    3   1    0    1    2    3 \cr
#' Q32    G    4   2    0    1    2    3 \cr
#' Q41    P    3   1    0    1    2    3 \cr
#' Q42    P    4   2    0    1    2    3"; \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. \cr
#'    v's are the category weight. (all natural)
#'
#'
#' @format A data frame with 8 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS21"



#' Small Item Weight Data Frame # 6.\cr
#' To be used in conjunction with paramS2.
#'
#' @details
#' name type ncat  w    v0   v1   v2   v3 \cr
#' Q11    B    2   1    0    1 ,, \cr
#' Q12    B    2   1    0    2 ,, \cr
#' Q21    B3   2   1    0    1 ,, \cr
#' Q22    B3   2   1    0    3 ,, \cr
#' Q31    G    3   1    0    1    2    3 \cr
#' Q32    G    4   1    0    1    3    5 \cr
#' Q41    P    3   1    0    2    3    4 \cr
#' Q42    P    4   1    0    0    0    3 \cr
#'    \cr
#'    item type = "B" or "B3" or "G" or "P" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. (all equal)\cr
#'    v's are the category weight
#'
#'
#' @format A data frame with 8 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS22"



#' Small Item Weight Data Frame #7
#' To be used in conjunction with paramS3\cr
#'
#' @details
#' \preformatted{
#' name  type ncat w   v0   v1   v2    v3
#' QB1   B   2     1     0   1   NA    NA
#' QB2   B2  2     1     0   1   NA    NA
#' QB3   B2  2     1     0   1   NA    NA
#' QB4   B3  2     1     0   1   2     NA
#' QG1   G   3     1     0   1   2     NA
#' QG2   G   3     1     0   1   2     NA
#' QG3   G   3     1     0   1   2     NA
#' QG4   G   3     1     0   1   2     NA
#' QG5   G   3     1     0   1   2     NA
#' QG6   G   3     1     0   1   2     NA
#' QG7   G   4     1     0   1   2      3
#' QG8   G   4     1     0   1   2      3
#' QPN1  PN  3     1     0   1   2     NA
#' QPN2  PN  3     1     0   1   2     NA
#' QPN3  PN  3     1     0   1   2     NA
#' QPN4  PN  3     1     0   1   2     NA
#' QPN5  PN  3     1     0   1   2     NA
#' QPN6  PN  3     1     0   1   2     NA
#' QPN7  PN  4     1     0   1   2      3
#' QPN8  PN  4     1     0   1   2      3
#' }
#'    \cr
#'    item type = "B" or "B3" or "G" or "PN" \cr
#'    ncat is the max # of categories \cr
#'    w is the item weight. (all equal)\cr
#'    v's are the category weight
#'
#'
#' @format A data frame with 20 rows and 8 variables
#' \describe{
#'  \item{name}{character:  Item name}
#'  \item{type}{character:  Item type}
#'  \item{ncat}{num: # of categories: 2 for binary items}
#'  \item{w}{num: item weight}
#'  \item{v0}{num: category weight for the zero-th category}
#'  \item{v1}{num: category weight for the 1st category}
#'  \item{v2}{num: category weight for the 2nd category}
#'  \item{v3}{num: category weight for the 3rd category}
#' }
#' @source Generated by author.
#'
"weightS3"














